importing the dependencies

In [25]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

Data collection and Analysis

In [26]:
df=pd.read_csv('diabetes.csv',header=0)

In [27]:
df.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   
5            5      116             74              0        0  25.6   
6            3       78             50             32       88  31.0   
7           10      115              0              0        0  35.3   
8            2      197             70             45      543  30.5   
9            8      125             96              0        0   0.0   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

In [28]:
# number of rows and columns in data frame
df.shape

(768, 9)

In [29]:
# getting the statistical measures of the data
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [30]:
df['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

0 -> Non diabetic    
1 -> diabetic

In [31]:
df.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [32]:
#Separating the data and labels
X = df.drop(columns = 'Outcome', axis = 1)
Y = df['Outcome']

Printing the X and Y data frames

In [33]:
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  


In [34]:
print(Y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


Data Standardization

In [35]:
scaler = StandardScaler()

In [36]:
scaler.fit(X)

StandardScaler()

In [37]:
standardized_data = scaler.transform(X)
standardized_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [38]:
X = standardized_data
Y = df['Outcome']

Spliting data for training and testing

In [39]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size =0.2, stratify = Y, random_state=2)

In [40]:
print(X.shape,X_train.shape,X_test.shape)

(768, 8) (614, 8) (154, 8)


Training the models

In [41]:
key = ['LogisticRegression','LinearDiscriminantAnalysis','SVC','DecisionTreeClassifier']
value = [LogisticRegression(),LinearDiscriminantAnalysis(),SVC(),DecisionTreeClassifier(splitter='best')]
models = dict(zip(key,value))
print(models)

{'LogisticRegression': LogisticRegression(), 'LinearDiscriminantAnalysis': LinearDiscriminantAnalysis(), 'SVC': SVC(), 'DecisionTreeClassifier': DecisionTreeClassifier()}


Model evaluation

Accuracy scores of each model

In [42]:
predicted =[]
for name,algo in models.items():
    model=algo
    model.fit(X_train,Y_train)
    predict = model.predict(X_test)
    acc = accuracy_score(Y_test, predict)
    predicted.append(acc)

In [43]:
df_accuracy=pd.DataFrame({'algo_name':key,
            'accuracy':predicted})
df_accuracy

algo_name  accuracy
0          LogisticRegression  0.759740
1  LinearDiscriminantAnalysis  0.753247
2                         SVC  0.727273
3      DecisionTreeClassifier  0.675325

Training the SVM model

In [48]:
classifier = svm.SVC(kernel = 'linear')

In [49]:
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

In [51]:
#accuracy score on training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)
print('accuract score of training data : ',training_data_accuracy)

accuract score of training data :  0.7866449511400652


In [52]:
#accuracy score on testing data
X_test_prediction = classifier.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction,Y_test)
print('accuract score of testing data : ',testing_data_accuracy)

accuract score of testing data :  0.7727272727272727


Making a Predictive System

In [44]:
input_data = (4,110,92,0,0,37.6,0.191,30)

#changing the input data into numpy array
input_data_as_numpy_array = np.array(input_data)

#Reshape the array as we are predicting for one instance
input_data_reshaped =  input_data_as_numpy_array.reshape(1,-1)

#standardize the input data
std_data = scaler.transform(input_data_reshaped)

In [45]:
std_data

array([[ 0.04601433, -0.34096773,  1.18359575, -1.28821221, -0.69289057,
         0.71168975, -0.84827977, -0.27575966]])

In [53]:
prediction = classifier.predict(std_data)
prediction

array([0], dtype=int64)

In [54]:
if prediction[0] == 0:
    print(" Person is not a diabetic patient")
else:
    print(" Person is diabetic patient")

 Person is not a diabetic patient
